spring:
  application:
    name: cards
  profiles:
    active: "prod"
  datasource:
    #url: jdbc:mysql://localhost:3308/cardsdb
    #username: root
    #password: root
    url: jdbc:mysql://localhost:3306/UdemyCards
    username: merve
    password: Merve123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true # Kayıtları çekmesini aktif et
    registerWithEureka: true # Kendi kendini kayıt etmesini aktif et
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info: #eureka serverda bu alan gözükür
  app:
    name: "cards"
    description: "Meryil Bank Card Application"
    version: "1.0.0"