spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3306/UdemyCards
    username: merve
    password: Merve123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

application:
  version: 1.0.0

server:
  port: 9000

logging:
  level:
    org.springframework: error

build:
  version: "3.0"

cards:
  message: "Welcome to MeryilBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@meryilbank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932