services:
  accounts:
    image: "merveyilmas/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - meryilbank
  loans:
    image: "merveyilmas/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - meryilbank
  cards:
    image: "merveyilmas/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - meryilbank
networks:
  meryilbank:
    driver: "bridge"