spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3306/UdemyLoans
    username: merve
    password: Merve123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

application:
  version: 1.0.0

server:
  port: 8090

logging:
  level:
    org.springframework: error
